services:
  mongo:
    image: mongo:8.0
    restart: always
    ports:
      - 52701:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dummy
      MONGO_INITDB_ROOT_PASSWORD: dummy
      MONGO_INITDB_DATABASE: confi
    volumes:
      - mongodata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongodata:
