services:
  mongo:
    image: mongo:8.0
    restart: always
    ports:
      - 52701:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dummy
      MONGO_INITDB_ROOT_PASSWORD: dummy
      MONGO_INITDB_DATABASE: confi
    volumes:
      - mongodata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000 # API port
      - 9001:9001 # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: confi-bucket
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mongodata:
  miniodata:
