/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ApiService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "ApiVpc": {
      "type": "sst.aws.Vpc"
    }
    "AppSync": {
      "type": "sst.aws.AppSync"
      "url": string
    }
    "AuthUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "AuthUserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "ClientStaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}